sudo: false

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3"

env:
  - DJANGO="Django<2.0"
  - DJANGO="Django<2.1"

matrix:
  exclude:
    - env: DJANGO="Django<2.1"
      python: "pypy"
    - env: DJANGO="Django<2.1"
      python: "2.7"

# Install dependencies.
install:
  - pip install -q $DJANGO
  - pip install -r requirements.txt

# Run tests.
script: python test.py
